---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.12.2
    app.quarkus.io/commit-id: db6b23151e5324d8a37123bfd1e9e98c165e75cc
    app.quarkus.io/vcs-uri: https://github.com/Tek3079/COMP655Final.git
    app.quarkus.io/build-timestamp: 2024-07-30 - 16:13:33 +0000
  labels:
    app.kubernetes.io/name: report-service
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/managed-by: quarkus
  name: report-service
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8083
  selector:
    app.kubernetes.io/name: report-service
    app.kubernetes.io/version: 1.0.0
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.12.2
    app.quarkus.io/commit-id: db6b23151e5324d8a37123bfd1e9e98c165e75cc
    app.quarkus.io/vcs-uri: https://github.com/Tek3079/COMP655Final.git
    app.quarkus.io/build-timestamp: 2024-07-30 - 16:13:33 +0000
  labels:
    app.kubernetes.io/name: report-service
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/managed-by: quarkus
  name: report-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: report-service
      app.kubernetes.io/version: 1.0.0
  template:
    metadata:
      annotations:
        app.quarkus.io/quarkus-version: 3.12.2
        app.quarkus.io/commit-id: db6b23151e5324d8a37123bfd1e9e98c165e75cc
        app.quarkus.io/vcs-uri: https://github.com/Tek3079/COMP655Final.git
        app.quarkus.io/build-timestamp: 2024-07-30 - 16:13:33 +0000
      labels:
        app.kubernetes.io/managed-by: quarkus
        app.kubernetes.io/name: report-service
        app.kubernetes.io/version: 1.0.0
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: docker.io/tek/report-service:1.0.0
          imagePullPolicy: Always
          name: report-service
          ports:
            - containerPort: 8083
              name: http
              protocol: TCP
